channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - numpy
  - pandas
  - pip
  - pip:
      - azureml-core
      - ipython
      - ipykernel
      - datasets
      - evaluate
      - azure-ai-ml
      - numpy
      - tensorflow==2.9
      - mlflow==2.4
      - accelerate==0.21.0
      - cffi==1.15.1
      - dill==0.3.6
      - google-api-core==2.11.0
      - ipython==8.8.0
      - numpy==1.23.5
      - packaging==21.3
      - protobuf==3.20.3
      - pyyaml==6.0
      - requests==2.28.2
      - safetensors==0.3.1
      - scikit-learn==1.2.2
      - scipy==1.10.1
      - torch==2.0.1
      - torchvision==0.15.2
      - transformers==4.29.0
      - xformers==0.0.20
name: testenv
