name: Trigger Automate-creation-env

on:
  workflow_dispatch:

jobs:
  trigger_workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Trigger son-azureml-oss-models Workflow
        run: |
          curl -X POST \
          -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/Konjarla-Vindya/son-azureml-oss-models/actions/workflows/automate-creation-env.yml/dispatches \
          -d '{"ref": "main", "inputs": {"branchName": "main", "environmentName": "staging"}}'
